const data = {
  tours: [
    {
      name: 'Tour du lịch Hàn Quốc',
      location: "Hàn Quốc",
      category: 'Tour',
      image: '/assets/images/tour/korea.jpg',
      info: {
        transport: 'Korean Air',
        time: '4 Ngày 4 đêm',
        period: '09 tháng 09',
        hotel: 'Ibis 4*',
      },
      isFavorite: false,
      price: 500,
      brand: 'AdoraTour',
      rating: 4.5,
      numReviews: 10,
      emptySeat: 25,
      description: 'Your favorite country in summer',
    },
    {
      name: 'Tour du lịch Nhật Bản',
      location: "Nhật Bản",
      category: 'Tour',
      image: '/assets/images/tour/japan.jpg',
      info: {
        transport: 'Japan Air',
        time: '4 Ngày 3 đêm',
        period: '09 tháng 10',
        hotel: '3*',
      },
      isFavorite: false,
      price: 500,
      brand: 'HanaTour',
      rating: 4.0,
      numReviews: 5,
      emptySeat: 25,
      description: 'Your favorite country in summer',
    },
    {
      name: 'Tour du lịch Đài Loan',
      location:"Đài Loan",
      category: 'Tour',
      image: '/assets/images/tour/taiwan.jpg',
      info: {
        transport: 'Eva Air',
        time: '5 Ngày 4 đêm',
        period: '08 tháng 09',
        hotel: '4*',
      },
      isFavorite: false,
      price: 500,
      brand: 'Dolphin',
      rating: 4.3,
      numReviews: 8,
      emptySeat: 25,
      description: 'Your favorite country in summer',
    },
    {
      name: 'Tour du lịch Thái Lan',
      location: 'Thái Lan',
      category: 'Tour',
      image: '/assets/images/tour/thailand.jpg',
      info: {
        transport: 'Nok Air',
        time: '5 Ngày 4 đêm',
        period: '19 tháng 09',
        hotel: 'Ibis 4*',
      },
      isFavorite: false,
      price: 500,
      brand: 'JPN',
      rating: 4.2,
      numReviews: 6,
      emptySeat: 25,
      description: 'Your favorite country in summer',
    },
    {
      name: 'Tour du lịch Singapore',
      location:"Singapore",
      category: 'Tour',
      image: '/assets/images/tour/singapore.jpg',
      info: {
        transport: 'Korean Air',
        time: '3 Ngày 2 đêm',
        period: '29 tháng 09',
        hotel: 'Ibis 3*',
      },
      isFavorite: false,
      price: 500,
      brand: 'Vietravel',
      rating: 4.4,
      numReviews: 12,
      emptySeat: 25,
      description: 'Your favorite country in summer',
    },
  ],
};

export default data;
